name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    environment: test
    strategy:
      matrix:
        node: [10,12,14]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os}}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node}}
    - run: npm ci
    - run: npm test
    - name: Hello Js action
      id: helloJs
      uses: IObregon-plain/formationJsAction@main
      with:
        who-to-greet: ${{secrets.MYNAME}}
    - run: echo "The time was ${{ steps.helloJs.outputs.time }}"

    - name: Hello Dcoker action
      id: helloDocker
      uses: IObregon-plain/formationDockerAction@main
      with:
        who-to-greet: ${{secrets.MYNAME}}
    - run: echo "The time was ${{ steps.helloDocker.outputs.time }}"